base_url = "https://docs.worldwidetelescope.org/infrastructure-guide/1/"
title = "WWT Infrastructure Guide"
description = "The AAS WorldWide Telescope Infrastructure manual."
theme = "wwtguide"

[extra]
github_base = "https://github.com/WorldWideTelescope/worldwide-telescope-infrastructure-guide"
google_analytics_id = "G-D1J49XX0CV"
