base_url = "//docs.worldwidetelescope.org/infrastructure-guide/1/"
title = "WWT Infrastructure Guide"
description = "The AAS WorldWide Telescope Infrastructure manual."
theme = "wwtguide"

[extra]
github_base = "//github.com/WorldWideTelescope/worldwide-telescope-infrastructure-guide"
google_analytics_id = "UA-107473046-3"
